---
abstract: 'Bioinformatics Utilities!'
author:
  - 'Wei Shen <shenwei356@gmail.com>'
build_requires:
  Test::More: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.132830'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: BioUtil
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.006
resources:
  repository: https://github.com/shenwei356/BioUtil.git
version: 2014.1115
